-- Insert 300 smaller/unknown teams for MiraclBet Manual Bets
INSERT INTO saved_teams (api_id, name, logo, country, country_flag) VALUES
(10000, 'Depok SC', 'https://media.api-sports.io/football/teams/10000.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10001, 'Real Kaunas', 'https://media.api-sports.io/football/teams/10001.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10002, 'Dynamo Tartu', 'https://media.api-sports.io/football/teams/10002.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10003, 'Rapid Jonava', 'https://media.api-sports.io/football/teams/10003.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10004, 'Kakamega Wanderers', 'https://media.api-sports.io/football/teams/10004.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10005, 'Mbarara Rovers', 'https://media.api-sports.io/football/teams/10005.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10006, 'Rapid Jijiga', 'https://media.api-sports.io/football/teams/10006.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10007, 'Sporting Kohtla-Jarve', 'https://media.api-sports.io/football/teams/10007.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10008, 'Gondar Town', 'https://media.api-sports.io/football/teams/10008.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10009, 'Viljandi United', 'https://media.api-sports.io/football/teams/10009.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10010, 'Semarang Villa', 'https://media.api-sports.io/football/teams/10010.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10011, 'Malindi SC', 'https://media.api-sports.io/football/teams/10011.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10012, 'Sliema SC', 'https://media.api-sports.io/football/teams/10012.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10013, 'Jelgava FC', 'https://media.api-sports.io/football/teams/10013.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10014, 'Inter Dire Dawa', 'https://media.api-sports.io/football/teams/10014.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10015, 'Mekelle United', 'https://media.api-sports.io/football/teams/10015.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10016, 'Shashamane Stars', 'https://media.api-sports.io/football/teams/10016.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10017, 'Rapid Nakuru', 'https://media.api-sports.io/football/teams/10017.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10018, 'Jekabpils Rovers', 'https://media.api-sports.io/football/teams/10018.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10019, 'Inter Da Nang', 'https://media.api-sports.io/football/teams/10019.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10020, 'Kakamega United', 'https://media.api-sports.io/football/teams/10020.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10021, 'Bekasi Wanderers', 'https://media.api-sports.io/football/teams/10021.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10022, 'AC Depok', 'https://media.api-sports.io/football/teams/10022.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10023, 'Addis Ababa Boys', 'https://media.api-sports.io/football/teams/10023.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10024, 'Maardu Athletic', 'https://media.api-sports.io/football/teams/10024.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10025, 'Eldoret SC', 'https://media.api-sports.io/football/teams/10025.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10026, 'Jijiga FC', 'https://media.api-sports.io/football/teams/10026.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10027, 'Garissa SC', 'https://media.api-sports.io/football/teams/10027.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10028, 'Nakuru Athletic', 'https://media.api-sports.io/football/teams/10028.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10029, 'Inter Chiang Mai', 'https://media.api-sports.io/football/teams/10029.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10030, 'Khon Kaen United', 'https://media.api-sports.io/football/teams/10030.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10031, 'Lokomotiv Narva', 'https://media.api-sports.io/football/teams/10031.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10032, 'AC Tangerang', 'https://media.api-sports.io/football/teams/10032.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10033, 'Mekelle Athletic', 'https://media.api-sports.io/football/teams/10033.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10034, 'Addis Ababa Rovers', 'https://media.api-sports.io/football/teams/10034.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10035, 'Awassa United', 'https://media.api-sports.io/football/teams/10035.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10036, 'Awassa FC', 'https://media.api-sports.io/football/teams/10036.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10037, 'Zanzibar United', 'https://media.api-sports.io/football/teams/10037.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10038, 'Marijampole SC', 'https://media.api-sports.io/football/teams/10038.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10039, 'Real Addis Ababa', 'https://media.api-sports.io/football/teams/10039.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10040, 'Kohtla-Jarve United', 'https://media.api-sports.io/football/teams/10040.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10041, 'Tabora FC', 'https://media.api-sports.io/football/teams/10041.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10042, 'Atletico Klaipeda', 'https://media.api-sports.io/football/teams/10042.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10043, 'Kitale City', 'https://media.api-sports.io/football/teams/10043.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10044, 'Gondar Stars', 'https://media.api-sports.io/football/teams/10044.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10045, 'Lokomotiv Surabaya', 'https://media.api-sports.io/football/teams/10045.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10046, 'Sillamae United', 'https://media.api-sports.io/football/teams/10046.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10047, 'Inter Addis Ababa', 'https://media.api-sports.io/football/teams/10047.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10048, 'Kohtla-Jarve SC', 'https://media.api-sports.io/football/teams/10048.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10049, 'Spartak Liepaja', 'https://media.api-sports.io/football/teams/10049.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10050, 'Vung Tau FC', 'https://media.api-sports.io/football/teams/10050.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10051, 'Atletico Kitale', 'https://media.api-sports.io/football/teams/10051.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10052, 'Makassar Stars', 'https://media.api-sports.io/football/teams/10052.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10053, 'Palembang Boys', 'https://media.api-sports.io/football/teams/10053.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10054, 'Bien Hoa Villa', 'https://media.api-sports.io/football/teams/10054.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10055, 'Can Tho Villa', 'https://media.api-sports.io/football/teams/10055.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10056, 'Marijampole Stars', 'https://media.api-sports.io/football/teams/10056.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10057, 'Siauliai SC', 'https://media.api-sports.io/football/teams/10057.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10058, 'Hamrun SC', 'https://media.api-sports.io/football/teams/10058.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10059, 'Ogre SC', 'https://media.api-sports.io/football/teams/10059.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10060, 'Lokomotiv Mbeya', 'https://media.api-sports.io/football/teams/10060.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10061, 'San Gwann Rovers', 'https://media.api-sports.io/football/teams/10061.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10062, 'Jekabpils United', 'https://media.api-sports.io/football/teams/10062.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10063, 'FC Zejtun', 'https://media.api-sports.io/football/teams/10063.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10064, 'Inter Tartu', 'https://media.api-sports.io/football/teams/10064.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10065, 'Hue Rovers', 'https://media.api-sports.io/football/teams/10065.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10066, 'FC Hat Yai', 'https://media.api-sports.io/football/teams/10066.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10067, 'Tartu FC', 'https://media.api-sports.io/football/teams/10067.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10068, 'Rapid Jinja', 'https://media.api-sports.io/football/teams/10068.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10069, 'Boma Wanderers', 'https://media.api-sports.io/football/teams/10069.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10070, 'Nairobi Rovers', 'https://media.api-sports.io/football/teams/10070.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10071, 'Morogoro City', 'https://media.api-sports.io/football/teams/10071.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10072, 'Surabaya SC', 'https://media.api-sports.io/football/teams/10072.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10073, 'Mombasa FC', 'https://media.api-sports.io/football/teams/10073.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10074, 'Bien Hoa Warriors', 'https://media.api-sports.io/football/teams/10074.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10075, 'Spartak Jimma', 'https://media.api-sports.io/football/teams/10075.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10076, 'Da Nang Warriors', 'https://media.api-sports.io/football/teams/10076.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10077, 'Jelgava SC', 'https://media.api-sports.io/football/teams/10077.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10078, 'Jimma Stars', 'https://media.api-sports.io/football/teams/10078.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10079, 'Spartak Kohtla-Jarve', 'https://media.api-sports.io/football/teams/10079.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10080, 'Hat Yai SC', 'https://media.api-sports.io/football/teams/10080.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10081, 'Garissa Boys', 'https://media.api-sports.io/football/teams/10081.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10082, 'Vung Tau United', 'https://media.api-sports.io/football/teams/10082.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10083, 'Chiang Mai Boys', 'https://media.api-sports.io/football/teams/10083.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10084, 'Atletico Vung Tau', 'https://media.api-sports.io/football/teams/10084.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10085, 'Rapid Daugavpils', 'https://media.api-sports.io/football/teams/10085.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10086, 'AC Bahir Dar', 'https://media.api-sports.io/football/teams/10086.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10087, 'Tabora FC', 'https://media.api-sports.io/football/teams/10087.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10088, 'Dodoma Town', 'https://media.api-sports.io/football/teams/10088.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10089, 'Dynamo Bien Hoa', 'https://media.api-sports.io/football/teams/10089.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10090, 'Jurmala SC', 'https://media.api-sports.io/football/teams/10090.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10091, 'Garissa Stars', 'https://media.api-sports.io/football/teams/10091.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10092, 'Shashamane United', 'https://media.api-sports.io/football/teams/10092.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10093, 'Riga FC', 'https://media.api-sports.io/football/teams/10093.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10094, 'Palembang United', 'https://media.api-sports.io/football/teams/10094.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10095, 'Ogre United', 'https://media.api-sports.io/football/teams/10095.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10096, 'Klaipeda Athletic', 'https://media.api-sports.io/football/teams/10096.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10097, 'Valmiera United', 'https://media.api-sports.io/football/teams/10097.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10098, 'Vilnius Boys', 'https://media.api-sports.io/football/teams/10098.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10099, 'Thika SC', 'https://media.api-sports.io/football/teams/10099.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10100, 'Hamrun FC', 'https://media.api-sports.io/football/teams/10100.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10101, 'Hat Yai United', 'https://media.api-sports.io/football/teams/10101.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10102, 'Liepaja Rovers', 'https://media.api-sports.io/football/teams/10102.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10103, 'Mazeikiai FC', 'https://media.api-sports.io/football/teams/10103.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10104, 'Rapid Gulu', 'https://media.api-sports.io/football/teams/10104.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10105, 'AC Mazeikiai', 'https://media.api-sports.io/football/teams/10105.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10106, 'Naxxar FC', 'https://media.api-sports.io/football/teams/10106.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10107, 'Hanoi United', 'https://media.api-sports.io/football/teams/10107.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10108, 'Jelgava United', 'https://media.api-sports.io/football/teams/10108.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10109, 'Jurmala Villa', 'https://media.api-sports.io/football/teams/10109.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10110, 'Surat Thani United', 'https://media.api-sports.io/football/teams/10110.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10111, 'Morogoro FC', 'https://media.api-sports.io/football/teams/10111.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10112, 'Atletico Mazeikiai', 'https://media.api-sports.io/football/teams/10112.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10113, 'Kuressaare Athletic', 'https://media.api-sports.io/football/teams/10113.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10114, 'Kuressaare SC', 'https://media.api-sports.io/football/teams/10114.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10115, 'Vinh SC', 'https://media.api-sports.io/football/teams/10115.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10116, 'Utena SC', 'https://media.api-sports.io/football/teams/10116.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10117, 'Bahir Dar SC', 'https://media.api-sports.io/football/teams/10117.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10118, 'Hoima Boys', 'https://media.api-sports.io/football/teams/10118.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10119, 'Inter Kohtla-Jarve', 'https://media.api-sports.io/football/teams/10119.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10120, 'Palembang FC', 'https://media.api-sports.io/football/teams/10120.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10121, 'Phuket United', 'https://media.api-sports.io/football/teams/10121.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10122, 'Inter Jinja', 'https://media.api-sports.io/football/teams/10122.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10123, 'Lira Boys', 'https://media.api-sports.io/football/teams/10123.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10124, 'Inter Hanoi', 'https://media.api-sports.io/football/teams/10124.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10125, 'Valmiera Villa', 'https://media.api-sports.io/football/teams/10125.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10126, 'Inter Vung Tau', 'https://media.api-sports.io/football/teams/10126.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10127, 'Inter Tartu', 'https://media.api-sports.io/football/teams/10127.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10128, 'Boma SC', 'https://media.api-sports.io/football/teams/10128.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10129, 'Rapid Dodoma', 'https://media.api-sports.io/football/teams/10129.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10130, 'Surabaya United', 'https://media.api-sports.io/football/teams/10130.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10131, 'Spartak Utena', 'https://media.api-sports.io/football/teams/10131.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10132, 'Hamrun Town', 'https://media.api-sports.io/football/teams/10132.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10133, 'Inter Depok', 'https://media.api-sports.io/football/teams/10133.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10134, 'Rapid Qormi', 'https://media.api-sports.io/football/teams/10134.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10135, 'Real Mbale', 'https://media.api-sports.io/football/teams/10135.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10136, 'Nakhon Ratchasima Warriors', 'https://media.api-sports.io/football/teams/10136.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10137, 'Inter Kahama', 'https://media.api-sports.io/football/teams/10137.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10138, 'AC Ventspils', 'https://media.api-sports.io/football/teams/10138.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10139, 'Sporting Daugavpils', 'https://media.api-sports.io/football/teams/10139.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10140, 'Alytus Villa', 'https://media.api-sports.io/football/teams/10140.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10141, 'Tangerang United', 'https://media.api-sports.io/football/teams/10141.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10142, 'Real Khon Kaen', 'https://media.api-sports.io/football/teams/10142.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10143, 'Siauliai Rovers', 'https://media.api-sports.io/football/teams/10143.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10144, 'Hanoi Warriors', 'https://media.api-sports.io/football/teams/10144.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10145, 'Bekasi Stars', 'https://media.api-sports.io/football/teams/10145.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10146, 'Can Tho SC', 'https://media.api-sports.io/football/teams/10146.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10147, 'AC Shashamane', 'https://media.api-sports.io/football/teams/10147.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10148, 'Mekelle SC', 'https://media.api-sports.io/football/teams/10148.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10149, 'Inter Viljandi', 'https://media.api-sports.io/football/teams/10149.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10150, 'Valmiera FC', 'https://media.api-sports.io/football/teams/10150.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10151, 'Tanga Athletic', 'https://media.api-sports.io/football/teams/10151.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10152, 'Klaipeda FC', 'https://media.api-sports.io/football/teams/10152.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10153, 'Atletico Ogre', 'https://media.api-sports.io/football/teams/10153.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10154, 'Semarang United', 'https://media.api-sports.io/football/teams/10154.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10155, 'Inter Bekasi', 'https://media.api-sports.io/football/teams/10155.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10156, 'Riga Villa', 'https://media.api-sports.io/football/teams/10156.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10157, 'Klaipeda Athletic', 'https://media.api-sports.io/football/teams/10157.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10158, 'San Gwann Rovers', 'https://media.api-sports.io/football/teams/10158.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10159, 'Marijampole United', 'https://media.api-sports.io/football/teams/10159.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10160, 'Jimma United', 'https://media.api-sports.io/football/teams/10160.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10161, 'Palembang FC', 'https://media.api-sports.io/football/teams/10161.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10162, 'Jinja United', 'https://media.api-sports.io/football/teams/10162.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10163, 'Bien Hoa SC', 'https://media.api-sports.io/football/teams/10163.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10164, 'Inter Da Nang', 'https://media.api-sports.io/football/teams/10164.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10165, 'FC Narva', 'https://media.api-sports.io/football/teams/10165.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10166, 'Sporting Vilnius', 'https://media.api-sports.io/football/teams/10166.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10167, 'Bekasi City', 'https://media.api-sports.io/football/teams/10167.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10168, 'Haiphong Boys', 'https://media.api-sports.io/football/teams/10168.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10169, 'Valletta SC', 'https://media.api-sports.io/football/teams/10169.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10170, 'Spartak Kohtla-Jarve', 'https://media.api-sports.io/football/teams/10170.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10171, 'Valmiera Town', 'https://media.api-sports.io/football/teams/10171.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10172, 'Inter Narva', 'https://media.api-sports.io/football/teams/10172.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10173, 'Inter Medan', 'https://media.api-sports.io/football/teams/10173.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10174, 'Rakvere City', 'https://media.api-sports.io/football/teams/10174.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10175, 'Vinh United', 'https://media.api-sports.io/football/teams/10175.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10176, 'Nha Trang Stars', 'https://media.api-sports.io/football/teams/10176.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10177, 'Addis Ababa SC', 'https://media.api-sports.io/football/teams/10177.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10178, 'Kahama United', 'https://media.api-sports.io/football/teams/10178.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10179, 'Sliema FC', 'https://media.api-sports.io/football/teams/10179.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10180, 'Jakarta Warriors', 'https://media.api-sports.io/football/teams/10180.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10181, 'Tartu Town', 'https://media.api-sports.io/football/teams/10181.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10182, 'Spartak Arusha', 'https://media.api-sports.io/football/teams/10182.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10183, 'Inter Parnu', 'https://media.api-sports.io/football/teams/10183.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10184, 'Saigon Boys', 'https://media.api-sports.io/football/teams/10184.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10185, 'Jakarta United', 'https://media.api-sports.io/football/teams/10185.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10186, 'Kampala Town', 'https://media.api-sports.io/football/teams/10186.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10187, 'Dire Dawa Warriors', 'https://media.api-sports.io/football/teams/10187.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10188, 'Inter Jonava', 'https://media.api-sports.io/football/teams/10188.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10189, 'Atletico Viljandi', 'https://media.api-sports.io/football/teams/10189.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10190, 'Lokomotiv Daugavpils', 'https://media.api-sports.io/football/teams/10190.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10191, 'Narva Boys', 'https://media.api-sports.io/football/teams/10191.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10192, 'Makassar United', 'https://media.api-sports.io/football/teams/10192.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10193, 'Tartu FC', 'https://media.api-sports.io/football/teams/10193.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10194, 'Jurmala United', 'https://media.api-sports.io/football/teams/10194.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10195, 'Awassa Wanderers', 'https://media.api-sports.io/football/teams/10195.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10196, 'Real Palembang', 'https://media.api-sports.io/football/teams/10196.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10197, 'FC Udon Thani', 'https://media.api-sports.io/football/teams/10197.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10198, 'AC Liepaja', 'https://media.api-sports.io/football/teams/10198.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10199, 'Hat Yai Boys', 'https://media.api-sports.io/football/teams/10199.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10200, 'Bien Hoa Athletic', 'https://media.api-sports.io/football/teams/10200.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10201, 'Panevezys United', 'https://media.api-sports.io/football/teams/10201.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10202, 'Da Nang Wanderers', 'https://media.api-sports.io/football/teams/10202.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10203, 'Surat Thani FC', 'https://media.api-sports.io/football/teams/10203.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10204, 'Dynamo Mbale', 'https://media.api-sports.io/football/teams/10204.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10205, 'Jijiga Athletic', 'https://media.api-sports.io/football/teams/10205.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10206, 'Rapid Udon Thani', 'https://media.api-sports.io/football/teams/10206.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10207, 'Atletico Bien Hoa', 'https://media.api-sports.io/football/teams/10207.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10208, 'Malindi Boys', 'https://media.api-sports.io/football/teams/10208.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10209, 'Rapid Ogre', 'https://media.api-sports.io/football/teams/10209.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10210, 'Liepaja Boys', 'https://media.api-sports.io/football/teams/10210.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10211, 'Inter Kasese', 'https://media.api-sports.io/football/teams/10211.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10212, 'Surat Thani Villa', 'https://media.api-sports.io/football/teams/10212.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10213, 'Spartak Eldoret', 'https://media.api-sports.io/football/teams/10213.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10214, 'AC Nakuru', 'https://media.api-sports.io/football/teams/10214.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10215, 'Valletta FC', 'https://media.api-sports.io/football/teams/10215.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10216, 'Inter Dire Dawa', 'https://media.api-sports.io/football/teams/10216.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10217, 'Da Nang FC', 'https://media.api-sports.io/football/teams/10217.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10218, 'San Gwann Stars', 'https://media.api-sports.io/football/teams/10218.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10219, 'FC Medan', 'https://media.api-sports.io/football/teams/10219.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10220, 'Valletta SC', 'https://media.api-sports.io/football/teams/10220.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10221, 'FC Maardu', 'https://media.api-sports.io/football/teams/10221.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10222, 'Arusha Athletic', 'https://media.api-sports.io/football/teams/10222.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10223, 'Kuressaare FC', 'https://media.api-sports.io/football/teams/10223.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10224, 'Lokomotiv Kaunas', 'https://media.api-sports.io/football/teams/10224.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10225, 'Thika City', 'https://media.api-sports.io/football/teams/10225.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10226, 'Sillamae United', 'https://media.api-sports.io/football/teams/10226.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10227, 'Real Semarang', 'https://media.api-sports.io/football/teams/10227.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10228, 'Eldoret FC', 'https://media.api-sports.io/football/teams/10228.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10229, 'Gondar FC', 'https://media.api-sports.io/football/teams/10229.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10230, 'Dynamo Tangerang', 'https://media.api-sports.io/football/teams/10230.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10231, 'Phuket Town', 'https://media.api-sports.io/football/teams/10231.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10232, 'Lokomotiv Morogoro', 'https://media.api-sports.io/football/teams/10232.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10233, 'Dire Dawa SC', 'https://media.api-sports.io/football/teams/10233.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10234, 'Surabaya United', 'https://media.api-sports.io/football/teams/10234.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10235, 'Kasese City', 'https://media.api-sports.io/football/teams/10235.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10236, 'Vung Tau Stars', 'https://media.api-sports.io/football/teams/10236.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10237, 'Atletico Marijampole', 'https://media.api-sports.io/football/teams/10237.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10238, 'Dodoma Stars', 'https://media.api-sports.io/football/teams/10238.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10239, 'Viljandi Athletic', 'https://media.api-sports.io/football/teams/10239.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10240, 'Thika Villa', 'https://media.api-sports.io/football/teams/10240.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10241, 'Spartak Kuressaare', 'https://media.api-sports.io/football/teams/10241.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10242, 'Valletta Town', 'https://media.api-sports.io/football/teams/10242.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10243, 'Atletico Zejtun', 'https://media.api-sports.io/football/teams/10243.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10244, 'Pattaya Boys', 'https://media.api-sports.io/football/teams/10244.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10245, 'Nakhon Ratchasima Stars', 'https://media.api-sports.io/football/teams/10245.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10246, 'Tangerang United', 'https://media.api-sports.io/football/teams/10246.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10247, 'Sporting Khon Kaen', 'https://media.api-sports.io/football/teams/10247.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10248, 'Real Kitale', 'https://media.api-sports.io/football/teams/10248.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10249, 'AC Kuressaare', 'https://media.api-sports.io/football/teams/10249.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10250, 'Rapid Bangkok', 'https://media.api-sports.io/football/teams/10250.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10251, 'Arusha SC', 'https://media.api-sports.io/football/teams/10251.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10252, 'Dessie Stars', 'https://media.api-sports.io/football/teams/10252.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10253, 'Marijampole City', 'https://media.api-sports.io/football/teams/10253.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10254, 'Awassa Villa', 'https://media.api-sports.io/football/teams/10254.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10255, 'Zabbar Villa', 'https://media.api-sports.io/football/teams/10255.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10256, 'Dynamo Awassa', 'https://media.api-sports.io/football/teams/10256.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10257, 'Maardu Town', 'https://media.api-sports.io/football/teams/10257.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10258, 'Zanzibar United', 'https://media.api-sports.io/football/teams/10258.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10259, 'Lira Stars', 'https://media.api-sports.io/football/teams/10259.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10260, 'Inter Gondar', 'https://media.api-sports.io/football/teams/10260.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10261, 'Jakarta SC', 'https://media.api-sports.io/football/teams/10261.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10262, 'Spartak Pattaya', 'https://media.api-sports.io/football/teams/10262.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10263, 'FC Mazeikiai', 'https://media.api-sports.io/football/teams/10263.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10264, 'Marijampole FC', 'https://media.api-sports.io/football/teams/10264.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10265, 'Maardu Rovers', 'https://media.api-sports.io/football/teams/10265.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10266, 'AC Masaka', 'https://media.api-sports.io/football/teams/10266.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10267, 'Makassar Wanderers', 'https://media.api-sports.io/football/teams/10267.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10268, 'Saigon United', 'https://media.api-sports.io/football/teams/10268.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10269, 'Valmiera SC', 'https://media.api-sports.io/football/teams/10269.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10270, 'Kisumu Town', 'https://media.api-sports.io/football/teams/10270.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10271, 'Sillamae Wanderers', 'https://media.api-sports.io/football/teams/10271.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10272, 'Rapid Arusha', 'https://media.api-sports.io/football/teams/10272.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10273, 'Tabora Wanderers', 'https://media.api-sports.io/football/teams/10273.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10274, 'Dynamo Zanzibar', 'https://media.api-sports.io/football/teams/10274.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10275, 'Real Parnu', 'https://media.api-sports.io/football/teams/10275.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10276, 'Jekabpils FC', 'https://media.api-sports.io/football/teams/10276.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10277, 'Mbarara FC', 'https://media.api-sports.io/football/teams/10277.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10278, 'Atletico Narva', 'https://media.api-sports.io/football/teams/10278.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10279, 'Dessie Villa', 'https://media.api-sports.io/football/teams/10279.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10280, 'Real Hoima', 'https://media.api-sports.io/football/teams/10280.png', 'Uganda', 'https://media.api-sports.io/flags/ug.svg'),
(10281, 'Valletta Rovers', 'https://media.api-sports.io/football/teams/10281.png', 'Malta', 'https://media.api-sports.io/flags/mt.svg'),
(10282, 'Kakamega FC', 'https://media.api-sports.io/football/teams/10282.png', 'Kenya', 'https://media.api-sports.io/flags/ke.svg'),
(10283, 'Inter Riga', 'https://media.api-sports.io/football/teams/10283.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10284, 'Mbeya United', 'https://media.api-sports.io/football/teams/10284.png', 'Tanzania', 'https://media.api-sports.io/flags/tz.svg'),
(10285, 'Nakhon Ratchasima Stars', 'https://media.api-sports.io/football/teams/10285.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10286, 'Surabaya SC', 'https://media.api-sports.io/football/teams/10286.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10287, 'Marijampole United', 'https://media.api-sports.io/football/teams/10287.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10288, 'Hue United', 'https://media.api-sports.io/football/teams/10288.png', 'Vietnam', 'https://media.api-sports.io/flags/vn.svg'),
(10289, 'Surabaya Stars', 'https://media.api-sports.io/football/teams/10289.png', 'Indonesia', 'https://media.api-sports.io/flags/id.svg'),
(10290, 'Kuressaare United', 'https://media.api-sports.io/football/teams/10290.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg'),
(10291, 'Inter Chiang Mai', 'https://media.api-sports.io/football/teams/10291.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10292, 'FC Alytus', 'https://media.api-sports.io/football/teams/10292.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10293, 'Mekelle FC', 'https://media.api-sports.io/football/teams/10293.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10294, 'Jonava City', 'https://media.api-sports.io/football/teams/10294.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10295, 'Mazeikiai City', 'https://media.api-sports.io/football/teams/10295.png', 'Lithuania', 'https://media.api-sports.io/flags/lt.svg'),
(10296, 'Mekelle SC', 'https://media.api-sports.io/football/teams/10296.png', 'Ethiopia', 'https://media.api-sports.io/flags/et.svg'),
(10297, 'Riga United', 'https://media.api-sports.io/football/teams/10297.png', 'Latvia', 'https://media.api-sports.io/flags/lv.svg'),
(10298, 'Sporting Surat Thani', 'https://media.api-sports.io/football/teams/10298.png', 'Thailand', 'https://media.api-sports.io/flags/th.svg'),
(10299, 'AC Narva', 'https://media.api-sports.io/football/teams/10299.png', 'Estonia', 'https://media.api-sports.io/flags/ee.svg');
