package database

import (
	"context"
	"log"
)

func SeedTeams(db *DB) {
	var count int
	err := db.Pool.QueryRow(context.Background(), "SELECT count(*) FROM saved_teams").Scan(&count)
	if err != nil {
		log.Printf("[seed] error checking saved_teams: %v", err)
		return
	}
	if count > 0 {
		return // already seeded
	}

	log.Println("[seed] inserting 300 international teams...")

	insertData := []struct {
		apiID                     int
		name, logo, country, flag string
	}{
		{1, "Arsenal", "https://media.api-sports.io/football/teams/1.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{2, "Aston Villa", "https://media.api-sports.io/football/teams/2.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{3, "Bournemouth", "https://media.api-sports.io/football/teams/3.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{4, "Brentford", "https://media.api-sports.io/football/teams/4.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{5, "Brighton", "https://media.api-sports.io/football/teams/5.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{6, "Burnley", "https://media.api-sports.io/football/teams/6.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{7, "Chelsea", "https://media.api-sports.io/football/teams/7.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{8, "Crystal Palace", "https://media.api-sports.io/football/teams/8.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{9, "Everton", "https://media.api-sports.io/football/teams/9.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{10, "Fulham", "https://media.api-sports.io/football/teams/10.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{11, "Liverpool", "https://media.api-sports.io/football/teams/11.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{12, "Luton Town", "https://media.api-sports.io/football/teams/12.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{13, "Manchester City", "https://media.api-sports.io/football/teams/13.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{14, "Manchester United", "https://media.api-sports.io/football/teams/14.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{15, "Newcastle United", "https://media.api-sports.io/football/teams/15.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{16, "Nottingham Forest", "https://media.api-sports.io/football/teams/16.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{17, "Sheffield United", "https://media.api-sports.io/football/teams/17.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{18, "Tottenham Hotspur", "https://media.api-sports.io/football/teams/18.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{19, "West Ham United", "https://media.api-sports.io/football/teams/19.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{20, "Wolverhampton Wanderers", "https://media.api-sports.io/football/teams/20.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{21, "Leicester City", "https://media.api-sports.io/football/teams/21.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{22, "Leeds United", "https://media.api-sports.io/football/teams/22.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{23, "Southampton", "https://media.api-sports.io/football/teams/23.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{24, "Norwich City", "https://media.api-sports.io/football/teams/24.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{25, "Watford", "https://media.api-sports.io/football/teams/25.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{26, "Sunderland", "https://media.api-sports.io/football/teams/26.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{27, "Middlesbrough", "https://media.api-sports.io/football/teams/27.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{28, "West Bromwich Albion", "https://media.api-sports.io/football/teams/28.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{29, "Stoke City", "https://media.api-sports.io/football/teams/29.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{30, "Swansea City", "https://media.api-sports.io/football/teams/30.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{31, "Cardiff City", "https://media.api-sports.io/football/teams/31.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{32, "Hull City", "https://media.api-sports.io/football/teams/32.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{33, "Queens Park Rangers", "https://media.api-sports.io/football/teams/33.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{34, "Bolton Wanderers", "https://media.api-sports.io/football/teams/34.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{35, "Blackburn Rovers", "https://media.api-sports.io/football/teams/35.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{36, "Portsmouth", "https://media.api-sports.io/football/teams/36.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{37, "Birmingham City", "https://media.api-sports.io/football/teams/37.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{38, "Derby County", "https://media.api-sports.io/football/teams/38.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{39, "Charlton Athletic", "https://media.api-sports.io/football/teams/39.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{40, "Wigan Athletic", "https://media.api-sports.io/football/teams/40.png", "England", "https://media.api-sports.io/flags/gb-eng.svg"},
		{41, "Real Madrid", "https://media.api-sports.io/football/teams/41.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{42, "Barcelona", "https://media.api-sports.io/football/teams/42.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{43, "Atletico Madrid", "https://media.api-sports.io/football/teams/43.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{44, "Sevilla", "https://media.api-sports.io/football/teams/44.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{45, "Real Sociedad", "https://media.api-sports.io/football/teams/45.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{46, "Villarreal", "https://media.api-sports.io/football/teams/46.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{47, "Real Betis", "https://media.api-sports.io/football/teams/47.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{48, "Athletic Club", "https://media.api-sports.io/football/teams/48.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{49, "Valencia", "https://media.api-sports.io/football/teams/49.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{50, "Osasuna", "https://media.api-sports.io/football/teams/50.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{51, "Celta Vigo", "https://media.api-sports.io/football/teams/51.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{52, "Rayo Vallecano", "https://media.api-sports.io/football/teams/52.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{53, "Girona", "https://media.api-sports.io/football/teams/53.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{54, "Mallorca", "https://media.api-sports.io/football/teams/54.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{55, "Getafe", "https://media.api-sports.io/football/teams/55.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{56, "Cadiz", "https://media.api-sports.io/football/teams/56.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{57, "Almeria", "https://media.api-sports.io/football/teams/57.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{58, "Granada", "https://media.api-sports.io/football/teams/58.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{59, "Las Palmas", "https://media.api-sports.io/football/teams/59.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{60, "Alaves", "https://media.api-sports.io/football/teams/60.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{61, "Espanyol", "https://media.api-sports.io/football/teams/61.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{62, "Levante", "https://media.api-sports.io/football/teams/62.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{63, "Elche", "https://media.api-sports.io/football/teams/63.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{64, "Valladolid", "https://media.api-sports.io/football/teams/64.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{65, "Eibar", "https://media.api-sports.io/football/teams/65.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{66, "Malaga", "https://media.api-sports.io/football/teams/66.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{67, "Deportivo La Coruna", "https://media.api-sports.io/football/teams/67.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{68, "Zaragoza", "https://media.api-sports.io/football/teams/68.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{69, "Sporting Gijon", "https://media.api-sports.io/football/teams/69.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{70, "Racing Santander", "https://media.api-sports.io/football/teams/70.png", "Spain", "https://media.api-sports.io/flags/es.svg"},
		{71, "Napoli", "https://media.api-sports.io/football/teams/71.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{72, "Lazio", "https://media.api-sports.io/football/teams/72.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{73, "Inter Milan", "https://media.api-sports.io/football/teams/73.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{74, "AC Milan", "https://media.api-sports.io/football/teams/74.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{75, "Atalanta", "https://media.api-sports.io/football/teams/75.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{76, "Roma", "https://media.api-sports.io/football/teams/76.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{77, "Juventus", "https://media.api-sports.io/football/teams/77.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{78, "Fiorentina", "https://media.api-sports.io/football/teams/78.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{79, "Bologna", "https://media.api-sports.io/football/teams/79.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{80, "Torino", "https://media.api-sports.io/football/teams/80.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{81, "Monza", "https://media.api-sports.io/football/teams/81.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{82, "Udinese", "https://media.api-sports.io/football/teams/82.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{83, "Sassuolo", "https://media.api-sports.io/football/teams/83.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{84, "Empoli", "https://media.api-sports.io/football/teams/84.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{85, "Salernitana", "https://media.api-sports.io/football/teams/85.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{86, "Lecce", "https://media.api-sports.io/football/teams/86.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{87, "Verona", "https://media.api-sports.io/football/teams/87.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{88, "Frosinone", "https://media.api-sports.io/football/teams/88.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{89, "Genoa", "https://media.api-sports.io/football/teams/89.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{90, "Cagliari", "https://media.api-sports.io/football/teams/90.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{91, "Sampdoria", "https://media.api-sports.io/football/teams/91.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{92, "Parma", "https://media.api-sports.io/football/teams/92.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{93, "Palermo", "https://media.api-sports.io/football/teams/93.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{94, "Bari", "https://media.api-sports.io/football/teams/94.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{95, "Brescia", "https://media.api-sports.io/football/teams/95.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{96, "Chievo", "https://media.api-sports.io/football/teams/96.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{97, "Catania", "https://media.api-sports.io/football/teams/97.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{98, "Siena", "https://media.api-sports.io/football/teams/98.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{99, "Livorno", "https://media.api-sports.io/football/teams/99.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{100, "Reggina", "https://media.api-sports.io/football/teams/100.png", "Italy", "https://media.api-sports.io/flags/it.svg"},
		{101, "Bayern Munich", "https://media.api-sports.io/football/teams/101.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{102, "Borussia Dortmund", "https://media.api-sports.io/football/teams/102.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{103, "RB Leipzig", "https://media.api-sports.io/football/teams/103.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{104, "Union Berlin", "https://media.api-sports.io/football/teams/104.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{105, "Freiburg", "https://media.api-sports.io/football/teams/105.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{106, "Bayer Leverkusen", "https://media.api-sports.io/football/teams/106.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{107, "Eintracht Frankfurt", "https://media.api-sports.io/football/teams/107.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{108, "Wolfsburg", "https://media.api-sports.io/football/teams/108.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{109, "Mainz 05", "https://media.api-sports.io/football/teams/109.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{110, "Borussia Monchengladbach", "https://media.api-sports.io/football/teams/110.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{111, "Koln", "https://media.api-sports.io/football/teams/111.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{112, "Hoffenheim", "https://media.api-sports.io/football/teams/112.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{113, "Werder Bremen", "https://media.api-sports.io/football/teams/113.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{114, "Bochum", "https://media.api-sports.io/football/teams/114.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{115, "Augsburg", "https://media.api-sports.io/football/teams/115.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{116, "Stuttgart", "https://media.api-sports.io/football/teams/116.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{117, "Heidenheim", "https://media.api-sports.io/football/teams/117.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{118, "Darmstadt", "https://media.api-sports.io/football/teams/118.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{119, "Schalke 04", "https://media.api-sports.io/football/teams/119.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{120, "Hertha BSC", "https://media.api-sports.io/football/teams/120.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{121, "Hamburger SV", "https://media.api-sports.io/football/teams/121.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{122, "Hannover 96", "https://media.api-sports.io/football/teams/122.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{123, "Nurnberg", "https://media.api-sports.io/football/teams/123.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{124, "Kaiserslautern", "https://media.api-sports.io/football/teams/124.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{125, "Arminia Bielefeld", "https://media.api-sports.io/football/teams/125.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{126, "Greuther Furth", "https://media.api-sports.io/football/teams/126.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{127, "Paderborn", "https://media.api-sports.io/football/teams/127.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{128, "Fortuna Dusseldorf", "https://media.api-sports.io/football/teams/128.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{129, "Ingolstadt", "https://media.api-sports.io/football/teams/129.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{130, "Braunschweig", "https://media.api-sports.io/football/teams/130.png", "Germany", "https://media.api-sports.io/flags/de.svg"},
		{131, "Paris Saint-Germain", "https://media.api-sports.io/football/teams/131.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{132, "Lens", "https://media.api-sports.io/football/teams/132.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{133, "Marseille", "https://media.api-sports.io/football/teams/133.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{134, "Rennes", "https://media.api-sports.io/football/teams/134.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{135, "Lille", "https://media.api-sports.io/football/teams/135.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{136, "Monaco", "https://media.api-sports.io/football/teams/136.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{137, "Lyon", "https://media.api-sports.io/football/teams/137.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{138, "Clermont", "https://media.api-sports.io/football/teams/138.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{139, "Nice", "https://media.api-sports.io/football/teams/139.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{140, "Lorient", "https://media.api-sports.io/football/teams/140.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{141, "Reims", "https://media.api-sports.io/football/teams/141.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{142, "Montpellier", "https://media.api-sports.io/football/teams/142.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{143, "Toulouse", "https://media.api-sports.io/football/teams/143.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{144, "Brest", "https://media.api-sports.io/football/teams/144.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{145, "Strasbourg", "https://media.api-sports.io/football/teams/145.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{146, "Nantes", "https://media.api-sports.io/football/teams/146.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{147, "Le Havre", "https://media.api-sports.io/football/teams/147.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{148, "Metz", "https://media.api-sports.io/football/teams/148.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{149, "Bordeaux", "https://media.api-sports.io/football/teams/149.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{150, "Saint-Etienne", "https://media.api-sports.io/football/teams/150.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{151, "Angers", "https://media.api-sports.io/football/teams/151.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{152, "Troyes", "https://media.api-sports.io/football/teams/152.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{153, "Ajaccio", "https://media.api-sports.io/football/teams/153.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{154, "Auxerre", "https://media.api-sports.io/football/teams/154.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{155, "Guingamp", "https://media.api-sports.io/football/teams/155.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{156, "Dijon", "https://media.api-sports.io/football/teams/156.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{157, "Amiens", "https://media.api-sports.io/football/teams/157.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{158, "Nimes", "https://media.api-sports.io/football/teams/158.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{159, "Caen", "https://media.api-sports.io/football/teams/159.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{160, "Evian", "https://media.api-sports.io/football/teams/160.png", "France", "https://media.api-sports.io/flags/fr.svg"},
		{161, "Benfica", "https://media.api-sports.io/football/teams/161.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{162, "Porto", "https://media.api-sports.io/football/teams/162.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{163, "Braga", "https://media.api-sports.io/football/teams/163.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{164, "Sporting CP", "https://media.api-sports.io/football/teams/164.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{165, "Vitoria de Guimaraes", "https://media.api-sports.io/football/teams/165.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{166, "Arouca", "https://media.api-sports.io/football/teams/166.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{167, "Chaves", "https://media.api-sports.io/football/teams/167.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{168, "Famalicao", "https://media.api-sports.io/football/teams/168.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{169, "Boavista", "https://media.api-sports.io/football/teams/169.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{170, "Casa Pia", "https://media.api-sports.io/football/teams/170.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{171, "Vizela", "https://media.api-sports.io/football/teams/171.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{172, "Rio Ave", "https://media.api-sports.io/football/teams/172.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{173, "Gil Vicente", "https://media.api-sports.io/football/teams/173.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{174, "Estoril", "https://media.api-sports.io/football/teams/174.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{175, "Portimonense", "https://media.api-sports.io/football/teams/175.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{176, "Moreirense", "https://media.api-sports.io/football/teams/176.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{177, "Farense", "https://media.api-sports.io/football/teams/177.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{178, "Estrela da Amadora", "https://media.api-sports.io/football/teams/178.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{179, "Belenenses", "https://media.api-sports.io/football/teams/179.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{180, "Maritimo", "https://media.api-sports.io/football/teams/180.png", "Portugal", "https://media.api-sports.io/flags/pt.svg"},
		{181, "Feyenoord", "https://media.api-sports.io/football/teams/181.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{182, "PSV Eindhoven", "https://media.api-sports.io/football/teams/182.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{183, "Ajax", "https://media.api-sports.io/football/teams/183.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{184, "AZ Alkmaar", "https://media.api-sports.io/football/teams/184.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{185, "Twente", "https://media.api-sports.io/football/teams/185.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{186, "Sparta Rotterdam", "https://media.api-sports.io/football/teams/186.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{187, "Utrecht", "https://media.api-sports.io/football/teams/187.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{188, "Heerenveen", "https://media.api-sports.io/football/teams/188.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{189, "RKC Waalwijk", "https://media.api-sports.io/football/teams/189.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{190, "Vitesse", "https://media.api-sports.io/football/teams/190.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{191, "Go Ahead Eagles", "https://media.api-sports.io/football/teams/191.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{192, "NEC Nijmegen", "https://media.api-sports.io/football/teams/192.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{193, "Fortuna Sittard", "https://media.api-sports.io/football/teams/193.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{194, "Volendam", "https://media.api-sports.io/football/teams/194.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{195, "Excelsior", "https://media.api-sports.io/football/teams/195.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{196, "Almere City", "https://media.api-sports.io/football/teams/196.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{197, "Heracles Almelo", "https://media.api-sports.io/football/teams/197.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{198, "PEC Zwolle", "https://media.api-sports.io/football/teams/198.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{199, "Groningen", "https://media.api-sports.io/football/teams/199.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{200, "Willem II", "https://media.api-sports.io/football/teams/200.png", "Netherlands", "https://media.api-sports.io/flags/nl.svg"},
		{201, "Antwerp", "https://media.api-sports.io/football/teams/201.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{202, "Genk", "https://media.api-sports.io/football/teams/202.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{203, "Union SG", "https://media.api-sports.io/football/teams/203.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{204, "Club Brugge", "https://media.api-sports.io/football/teams/204.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{205, "Gent", "https://media.api-sports.io/football/teams/205.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{206, "Standard Liege", "https://media.api-sports.io/football/teams/206.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{207, "Cercle Brugge", "https://media.api-sports.io/football/teams/207.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{208, "Charleroi", "https://media.api-sports.io/football/teams/208.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{209, "Anderlecht", "https://media.api-sports.io/football/teams/209.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{210, "OH Leuven", "https://media.api-sports.io/football/teams/210.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{211, "Mechelen", "https://media.api-sports.io/football/teams/211.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{212, "Sint-Truiden", "https://media.api-sports.io/football/teams/212.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{213, "Kortrijk", "https://media.api-sports.io/football/teams/213.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{214, "Eupen", "https://media.api-sports.io/football/teams/214.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{215, "Oostende", "https://media.api-sports.io/football/teams/215.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{216, "Westerlo", "https://media.api-sports.io/football/teams/216.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{217, "RWD Molenbeek", "https://media.api-sports.io/football/teams/217.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{218, "Zulte Waregem", "https://media.api-sports.io/football/teams/218.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{219, "Beveren", "https://media.api-sports.io/football/teams/219.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{220, "Lierse", "https://media.api-sports.io/football/teams/220.png", "Belgium", "https://media.api-sports.io/flags/be.svg"},
		{221, "Galatasaray", "https://media.api-sports.io/football/teams/221.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{222, "Fenerbahce", "https://media.api-sports.io/football/teams/222.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{223, "Besiktas", "https://media.api-sports.io/football/teams/223.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{224, "Adana Demirspor", "https://media.api-sports.io/football/teams/224.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{225, "Istanbul Basaksehir", "https://media.api-sports.io/football/teams/225.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{226, "Trabzonspor", "https://media.api-sports.io/football/teams/226.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{227, "Kayserispor", "https://media.api-sports.io/football/teams/227.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{228, "Konyaspor", "https://media.api-sports.io/football/teams/228.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{229, "Fatih Karagumruk", "https://media.api-sports.io/football/teams/229.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{230, "Alanyaspor", "https://media.api-sports.io/football/teams/230.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{231, "Kasimpasa", "https://media.api-sports.io/football/teams/231.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{232, "Antalyaspor", "https://media.api-sports.io/football/teams/232.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{233, "Sivasspor", "https://media.api-sports.io/football/teams/233.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{234, "Gaziantep", "https://media.api-sports.io/football/teams/234.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{235, "Pendikspor", "https://media.api-sports.io/football/teams/235.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{236, "Samsunspor", "https://media.api-sports.io/football/teams/236.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{237, "Caykur Rizespor", "https://media.api-sports.io/football/teams/237.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{238, "Ankaragucu", "https://media.api-sports.io/football/teams/238.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{239, "Bursaspor", "https://media.api-sports.io/football/teams/239.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{240, "Goztepe", "https://media.api-sports.io/football/teams/240.png", "Turkey", "https://media.api-sports.io/flags/tr.svg"},
		{241, "Celtic", "https://media.api-sports.io/football/teams/241.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{242, "Rangers", "https://media.api-sports.io/football/teams/242.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{243, "Aberdeen", "https://media.api-sports.io/football/teams/243.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{244, "Heart of Midlothian", "https://media.api-sports.io/football/teams/244.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{245, "Hibernian", "https://media.api-sports.io/football/teams/245.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{246, "St Mirren", "https://media.api-sports.io/football/teams/246.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{247, "Motherwell", "https://media.api-sports.io/football/teams/247.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{248, "Livingston", "https://media.api-sports.io/football/teams/248.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{249, "Kilmarnock", "https://media.api-sports.io/football/teams/249.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{250, "Ross County", "https://media.api-sports.io/football/teams/250.png", "Scotland", "https://media.api-sports.io/flags/gb-sct.svg"},
		{251, "Palmeiras", "https://media.api-sports.io/football/teams/251.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{252, "Internacional", "https://media.api-sports.io/football/teams/252.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{253, "Fluminense", "https://media.api-sports.io/football/teams/253.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{254, "Corinthians", "https://media.api-sports.io/football/teams/254.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{255, "Flamengo", "https://media.api-sports.io/football/teams/255.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{256, "Athletico Paranaense", "https://media.api-sports.io/football/teams/256.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{257, "Atletico Mineiro", "https://media.api-sports.io/football/teams/257.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{258, "Fortaleza", "https://media.api-sports.io/football/teams/258.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{259, "Sao Paulo", "https://media.api-sports.io/football/teams/259.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{260, "America Mineiro", "https://media.api-sports.io/football/teams/260.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{261, "Botafogo", "https://media.api-sports.io/football/teams/261.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{262, "Santos", "https://media.api-sports.io/football/teams/262.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{263, "Goias", "https://media.api-sports.io/football/teams/263.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{264, "Red Bull Bragantino", "https://media.api-sports.io/football/teams/264.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{265, "Coritiba", "https://media.api-sports.io/football/teams/265.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{266, "Cuiaba", "https://media.api-sports.io/football/teams/266.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{267, "Gremio", "https://media.api-sports.io/football/teams/267.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{268, "Bahia", "https://media.api-sports.io/football/teams/268.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{269, "Cruzeiro", "https://media.api-sports.io/football/teams/269.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{270, "Vasco da Gama", "https://media.api-sports.io/football/teams/270.png", "Brazil", "https://media.api-sports.io/flags/br.svg"},
		{271, "Boca Juniors", "https://media.api-sports.io/football/teams/271.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{272, "Racing Club", "https://media.api-sports.io/football/teams/272.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{273, "River Plate", "https://media.api-sports.io/football/teams/273.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{274, "Argentinos Juniors", "https://media.api-sports.io/football/teams/274.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{275, "Huracan", "https://media.api-sports.io/football/teams/275.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{276, "Gimnasia La Plata", "https://media.api-sports.io/football/teams/276.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{277, "Defensa y Justicia", "https://media.api-sports.io/football/teams/277.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{278, "Tigre", "https://media.api-sports.io/football/teams/278.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{279, "Newells Old Boys", "https://media.api-sports.io/football/teams/279.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{280, "Estudiantes", "https://media.api-sports.io/football/teams/280.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{281, "San Lorenzo", "https://media.api-sports.io/football/teams/281.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{282, "Independiente", "https://media.api-sports.io/football/teams/282.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{283, "Velez Sarsfield", "https://media.api-sports.io/football/teams/283.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{284, "Talleres", "https://media.api-sports.io/football/teams/284.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{285, "Rosario Central", "https://media.api-sports.io/football/teams/285.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{286, "Lanus", "https://media.api-sports.io/football/teams/286.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{287, "Banfield", "https://media.api-sports.io/football/teams/287.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{288, "Union", "https://media.api-sports.io/football/teams/288.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{289, "Colon", "https://media.api-sports.io/football/teams/289.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{290, "Arsenal de Sarandi", "https://media.api-sports.io/football/teams/290.png", "Argentina", "https://media.api-sports.io/flags/ar.svg"},
		{291, "Los Angeles FC", "https://media.api-sports.io/football/teams/291.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{292, "Philadelphia Union", "https://media.api-sports.io/football/teams/292.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{293, "CF Montreal", "https://media.api-sports.io/football/teams/293.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{294, "Austin FC", "https://media.api-sports.io/football/teams/294.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{295, "New York City FC", "https://media.api-sports.io/football/teams/295.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{296, "New York Red Bulls", "https://media.api-sports.io/football/teams/296.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{297, "FC Dallas", "https://media.api-sports.io/football/teams/297.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{298, "LA Galaxy", "https://media.api-sports.io/football/teams/298.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{299, "Nashville SC", "https://media.api-sports.io/football/teams/299.png", "USA", "https://media.api-sports.io/flags/us.svg"},
		{300, "Inter Miami", "https://media.api-sports.io/football/teams/300.png", "USA", "https://media.api-sports.io/flags/us.svg"},
	}

	for _, d := range insertData {
		_, err := db.Pool.Exec(context.Background(),
			"INSERT INTO saved_teams (api_id, name, logo, country, country_flag) VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING",
			d.apiID, d.name, d.logo, d.country, d.flag,
		)
		if err != nil {
			log.Printf("[seed] failed to insert team %s: %v", d.name, err)
		}
	}

	log.Println("[seed] finished inserting teams.")
}
